/**
 * @tx/types - Shared TypeScript types for tx
 *
 * Effect Schema definitions providing both compile-time types and runtime validation.
 * Works with any runtime (Node, Bun, Deno).
 *
 * @example
 * ```typescript
 * import { Task, TaskWithDeps, TaskId, TaskStatus } from "./index.js";
 * import { TaskSchema, TaskWithDepsSchema } from "./index.js";
 * import { Learning, LearningWithScore } from "./index.js";
 * import { Attempt, Run } from "./index.js";
 *
 * // Or import from specific modules:
 * import { TaskSchema, type Task, type TaskWithDeps } from "@tx/types/task";
 * import { LearningSchema, type Learning } from "@tx/types/learning";
 * ```
 */

// Task types & schemas
export {
  TASK_STATUSES,
  TASK_ASSIGNEE_TYPES,
  VALID_TRANSITIONS,
  TASK_ID_PATTERN,
  TaskStatusSchema,
  TaskAssigneeTypeSchema,
  TaskIdSchema,
  TaskSchema,
  TaskLinkedDocRefSchema,
  TaskWithDepsSchema,
  TaskTreeSchema,
  TaskDependencySchema,
  CreateTaskInputSchema,
  UpdateTaskInputSchema,
  TaskCursorSchema,
  TaskFilterSchema,
  isValidTaskId,
  assertTaskId,
  InvalidTaskIdError,
  isValidTaskStatus,
  assertTaskStatus,
  InvalidTaskStatusError,
  type TaskStatus,
  type TaskAssigneeType,
  type TaskId,
  type Task,
  type TaskLinkedDocRef,
  type TaskWithDeps,
  type TaskTree,
  type TaskDependency,
  type CreateTaskInput,
  type UpdateTaskInput,
  type TaskFilter,
  type TaskCursor,
  type TaskRow,
  type DependencyRow,
} from "./task.js";

// Doc types & schemas (docs-as-primitives, DD-023)
export {
  DOC_STABLE_ID_PATTERN,
  DOC_KINDS,
  DOC_STATUSES,
  DOC_LINK_TYPES,
  TASK_DOC_LINK_TYPES,
  INVARIANT_ENFORCEMENT_TYPES,
  INVARIANT_STATUSES,
  INVARIANT_SOURCES,
  MD_DOC_KINDS,
  MD_SPEC_TYPES,
  MD_SPEC_STATUSES,
  MD_EARS_REQUIREMENT_KINDS,
  MD_EARS_PRIORITIES,
  MD_VERIFICATION_TEST_TYPES,
  MD_INTERFACE_TYPES,
  MD_INVARIANT_SEVERITIES,
  MD_REQUIRED_SECTIONS_BY_SPEC_TYPE,
  EARS_PATTERNS,
  DocKindSchema,
  SPEC_TYPE_NAME_PATTERN,
  isBuiltinDocKind,
  asDocKind,
  MdDocKindSchema,
  MdSpecTypeSchema,
  MdSpecStatusSchema,
  DocStatusSchema,
  DocLinkTypeSchema,
  TaskDocLinkTypeSchema,
  DocIdSchema,
  DocStableIdSchema,
  DocSchema,
  DocWithLinksSchema,
  DocLinkSchema,
  TaskDocLinkSchema,
  CreateDocInputSchema,
  InvariantEnforcementSchema,
  InvariantStatusSchema,
  InvariantSourceSchema,
  InvariantIdSchema,
  InvariantSchema,
  InvariantCheckSchema,
  UpsertInvariantInputSchema,
  RecordInvariantCheckInputSchema,
  EarsPatternSchema,
  renderEarsRule,
  EarsPrioritySchema,
  EarsRequirementIdSchema,
  EarsRequirementSchema,
  YamlEarsRequirementSchema,
  MdNameSchema,
  MdDateSchema,
  MdFrontmatterSchema,
  MdEarsRequirementKindSchema,
  MdEarsPrioritySchema,
  MdEarsRequirementIdSchema,
  MdEarsRequirementSchema,
  MdInvariantSeveritySchema,
  MdInvariantIdSchema,
  MdInvariantSchema,
  MdVerificationTestTypeSchema,
  MdVerificationSchema,
  MdInterfaceTypeSchema,
  MdInterfaceSchema,
  MdFailureModeSchema,
  MdAcceptanceCriterionIdSchema,
  MdAcceptanceCriterionSchema,
  MdSectionSchema,
  MdEmbeddedBlocksSchema,
  MdParsedSpecDocSchema,
  MdParsedTaskDocSchema,
  MdParsedDocSchema,
  TraceabilityLevelSchema,
  TraceabilityRowSchema,
  YamlInvariantSchema,
  FailureModeSchema,
  EdgeCaseSchema,
  ActorSchema,
  UseCaseSchema,
  AppliesToSchema,
  DecisionLogEntrySchema,
  OverviewContentSchema,
  PrdContentSchema,
  DesignContentSchema,
  RequirementContentSchema,
  SystemDesignContentSchema,
  DOC_CONTENT_SCHEMAS,
  TRACEABILITY_LEVELS,
  DocGraphNodeSchema,
  DocGraphEdgeSchema,
  DocGraphSchema,
  isValidDocKind,
  InvalidDocKindError,
  assertDocKind,
  isValidDocStatus,
  InvalidDocStatusError,
  assertDocStatus,
  isValidDocLinkType,
  InvalidDocLinkTypeError,
  assertDocLinkType,
  type DocKind,
  type DocStatus,
  type MdDocKind,
  type MdSpecType,
  type MdSpecStatus,
  type DocLinkType,
  type TaskDocLinkType,
  type DocId,
  type DocStableId,
  type Doc,
  type DocWithLinks,
  type DocLink,
  type TaskDocLink,
  type CreateDocInput,
  type InvariantEnforcement,
  type InvariantStatus,
  type InvariantSource,
  type InvariantId,
  type Invariant,
  type InvariantCheck,
  type UpsertInvariantInput,
  type RecordInvariantCheckInput,
  type EarsPattern,
  type EarsPriority,
  type EarsRequirementId,
  type EarsRequirement,
  type YamlEarsRequirement,
  type MdName,
  type MdDate,
  type MdFrontmatter,
  type MdEarsRequirementKind,
  type MdEarsPriority,
  type MdEarsRequirementId,
  type MdEarsRequirement,
  type MdInvariantSeverity,
  type MdInvariantId,
  type MdInvariant,
  type MdVerificationTestType,
  type MdVerification,
  type MdInterfaceType,
  type MdInterface,
  type MdFailureMode,
  type MdAcceptanceCriterionId,
  type MdAcceptanceCriterion,
  type MdSection,
  type MdEmbeddedBlocks,
  type MdParsedSpecDoc,
  type MdParsedTaskDoc,
  type MdParsedDoc,
  type TraceabilityLevel,
  type TraceabilityRow,
  type YamlInvariant,
  type FailureMode,
  type EdgeCase,
  type Actor,
  type UseCase,
  type AppliesTo,
  type DecisionLogEntry,
  type OverviewContent,
  type PrdContent,
  type DesignContent,
  type RequirementContent,
  type SystemDesignContent,
  type DocGraphNode,
  type DocGraphEdge,
  type DocGraph,
  type DocRow,
  type DocLinkRow,
  type TaskDocLinkRow,
  type InvariantRow,
  type InvariantCheckRow,
} from "./doc.js"

// Spec traceability types & schemas
export {
  SPEC_DISCOVERY_METHODS,
  SPEC_SCOPE_TYPES,
  SPEC_PHASES,
  SpecDiscoveryMethodSchema,
  SpecScopeTypeSchema,
  SpecPhaseSchema,
  SpecTestIdSchema,
  SpecTestSchema,
  SpecTestRunSchema,
  SpecSignoffSchema,
  SpecScopeFilterSchema,
  SpecPruneCandidateSchema,
  DiscoverResultSchema,
  FciResultSchema,
  SpecTestLatestRunSchema,
  TraceabilityMatrixTestSchema,
  TraceabilityMatrixEntrySchema,
  TraceabilityMatrixSchema,
  BatchRunInputSchema,
  type SpecDiscoveryMethod,
  type SpecScopeType,
  type SpecPhase,
  type SpecTestId,
  type SpecTest,
  type SpecTestRun,
  type SpecSignoff,
  type SpecScopeFilter,
  type SpecPruneCandidate,
  type DiscoverResult,
  type FciResult,
  type SpecTestLatestRun,
  type TraceabilityMatrixTest,
  type TraceabilityMatrixEntry,
  type TraceabilityMatrix,
  type BatchRunInput,
  type SpecTestRow,
  type SpecTestRunRow,
  type SpecSignoffRow,
} from "./spec-trace.js"

// Decision types & schemas (spec-driven development triangle)
export {
  DECISION_STATUSES,
  DECISION_SOURCES,
  DecisionStatusSchema,
  DecisionSourceSchema,
  DecisionIdSchema,
  DecisionSchema,
  CreateDecisionInputSchema,
  ReviewDecisionInputSchema,
  DecisionSerializedSchema,
  serializeDecision,
  isValidDecisionStatus,
  isValidDecisionSource,
  type DecisionStatus,
  type DecisionSource,
  type DecisionId,
  type Decision,
  type CreateDecisionInput,
  type ReviewDecisionInput,
  type DecisionSerialized,
  type DecisionRow,
} from "./decision.js"

export * from "./response.js"
