// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "prd/prd-001-core-task-management.mdx": () => import("../content/docs/prd/prd-001-core-task-management.mdx?collection=docs"), "prd/prd-002-hierarchical-task-structure.mdx": () => import("../content/docs/prd/prd-002-hierarchical-task-structure.mdx?collection=docs"), "prd/prd-003-dependency-blocking-system.mdx": () => import("../content/docs/prd/prd-003-dependency-blocking-system.mdx?collection=docs"), "prd/prd-004-task-scoring-prioritization.mdx": () => import("../content/docs/prd/prd-004-task-scoring-prioritization.mdx?collection=docs"), "prd/prd-005-llm-deduplication.mdx": () => import("../content/docs/prd/prd-005-llm-deduplication.mdx?collection=docs"), "prd/prd-006-task-compaction-learnings.mdx": () => import("../content/docs/prd/prd-006-task-compaction-learnings.mdx?collection=docs"), "prd/prd-007-multi-interface-integration.mdx": () => import("../content/docs/prd/prd-007-multi-interface-integration.mdx?collection=docs"), "prd/prd-008-observability-opentelemetry.mdx": () => import("../content/docs/prd/prd-008-observability-opentelemetry.mdx?collection=docs"), "prd/prd-009-jsonl-git-sync.mdx": () => import("../content/docs/prd/prd-009-jsonl-git-sync.mdx?collection=docs"), "prd/prd-010-contextual-learnings-system.mdx": () => import("../content/docs/prd/prd-010-contextual-learnings-system.mdx?collection=docs"), "prd/prd-010-dashboard-ux.mdx": () => import("../content/docs/prd/prd-010-dashboard-ux.mdx?collection=docs"), "prd/prd-011-claude-code-hooks.mdx": () => import("../content/docs/prd/prd-011-claude-code-hooks.mdx?collection=docs"), "prd/prd-012-bun-single-binary.mdx": () => import("../content/docs/prd/prd-012-bun-single-binary.mdx?collection=docs"), "prd/prd-013-dashboard-ux.mdx": () => import("../content/docs/prd/prd-013-dashboard-ux.mdx?collection=docs"), "prd/prd-013-test-utilities.mdx": () => import("../content/docs/prd/prd-013-test-utilities.mdx?collection=docs"), "prd/prd-014-graph-schema-edges.mdx": () => import("../content/docs/prd/prd-014-graph-schema-edges.mdx?collection=docs"), "prd/prd-015-jsonl-daemon-promotion.mdx": () => import("../content/docs/prd/prd-015-jsonl-daemon-promotion.mdx?collection=docs"), "prd/prd-016-graph-expansion-retrieval.mdx": () => import("../content/docs/prd/prd-016-graph-expansion-retrieval.mdx?collection=docs"), "prd/prd-017-invalidation-maintenance.mdx": () => import("../content/docs/prd/prd-017-invalidation-maintenance.mdx?collection=docs"), "prd/prd-018-worker-orchestration.mdx": () => import("../content/docs/prd/prd-018-worker-orchestration.mdx?collection=docs"), }),
};
export default browserCollections;