// @ts-nocheck
import * as __fd_glob_58 from "../content/docs/primitives/sync.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/primitives/ready.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/primitives/learning.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/primitives/invariants.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/primitives/index.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/primitives/inbox.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/primitives/handoff.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/primitives/done.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/primitives/docs.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/primitives/context.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/primitives/claim.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/primitives/checkpoint.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/primitives/block.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/prd/prd-018-worker-orchestration.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/prd/prd-017-invalidation-maintenance.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/prd/prd-016-graph-expansion-retrieval.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/prd/prd-015-jsonl-daemon-promotion.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/prd/prd-014-graph-schema-edges.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/prd/prd-013-test-utilities.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/prd/prd-013-dashboard-ux.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/prd/prd-012-bun-single-binary.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/prd/prd-011-claude-code-hooks.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/prd/prd-010-dashboard-ux.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/prd/prd-010-contextual-learnings-system.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/prd/prd-009-jsonl-git-sync.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/prd/prd-008-observability-opentelemetry.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/prd/prd-007-multi-interface-integration.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/prd/prd-006-task-compaction-learnings.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/prd/prd-005-llm-deduplication.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/prd/prd-004-task-scoring-prioritization.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/prd/prd-003-dependency-blocking-system.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/prd/prd-002-hierarchical-task-structure.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/prd/prd-001-core-task-management.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/design/dd-018-worker-orchestration.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/design/dd-017-invalidation-maintenance.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/design/dd-016-graph-expansion-retrieval.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/design/dd-015-jsonl-daemon-promotion.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/design/dd-014-graph-schema-edges.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/design/dd-013-test-utilities.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/design/dd-012-dashboard-ux.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/design/dd-011-claude-code-hooks.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/design/dd-010-learnings-search-retrieval.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/design/dd-010-dashboard-ux.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/design/dd-009-jsonl-git-sync.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/design/dd-008-opentelemetry-integration.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/design/dd-007-testing-strategy.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/design/dd-006-llm-integration.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/design/dd-005-mcp-agent-sdk-integration.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/design/dd-004-ready-detection-algorithm.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/design/dd-003-cli-implementation.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/design/dd-002-effect-ts-service-layer.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/design/dd-001-data-model-storage.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/getting-started.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/agent-sdk.mdx?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/primitives/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/prd/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/design/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "design/meta.json": __fd_glob_1, "prd/meta.json": __fd_glob_2, "primitives/meta.json": __fd_glob_3, }, {"agent-sdk.mdx": __fd_glob_4, "getting-started.mdx": __fd_glob_5, "index.mdx": __fd_glob_6, "design/dd-001-data-model-storage.mdx": __fd_glob_7, "design/dd-002-effect-ts-service-layer.mdx": __fd_glob_8, "design/dd-003-cli-implementation.mdx": __fd_glob_9, "design/dd-004-ready-detection-algorithm.mdx": __fd_glob_10, "design/dd-005-mcp-agent-sdk-integration.mdx": __fd_glob_11, "design/dd-006-llm-integration.mdx": __fd_glob_12, "design/dd-007-testing-strategy.mdx": __fd_glob_13, "design/dd-008-opentelemetry-integration.mdx": __fd_glob_14, "design/dd-009-jsonl-git-sync.mdx": __fd_glob_15, "design/dd-010-dashboard-ux.mdx": __fd_glob_16, "design/dd-010-learnings-search-retrieval.mdx": __fd_glob_17, "design/dd-011-claude-code-hooks.mdx": __fd_glob_18, "design/dd-012-dashboard-ux.mdx": __fd_glob_19, "design/dd-013-test-utilities.mdx": __fd_glob_20, "design/dd-014-graph-schema-edges.mdx": __fd_glob_21, "design/dd-015-jsonl-daemon-promotion.mdx": __fd_glob_22, "design/dd-016-graph-expansion-retrieval.mdx": __fd_glob_23, "design/dd-017-invalidation-maintenance.mdx": __fd_glob_24, "design/dd-018-worker-orchestration.mdx": __fd_glob_25, "prd/prd-001-core-task-management.mdx": __fd_glob_26, "prd/prd-002-hierarchical-task-structure.mdx": __fd_glob_27, "prd/prd-003-dependency-blocking-system.mdx": __fd_glob_28, "prd/prd-004-task-scoring-prioritization.mdx": __fd_glob_29, "prd/prd-005-llm-deduplication.mdx": __fd_glob_30, "prd/prd-006-task-compaction-learnings.mdx": __fd_glob_31, "prd/prd-007-multi-interface-integration.mdx": __fd_glob_32, "prd/prd-008-observability-opentelemetry.mdx": __fd_glob_33, "prd/prd-009-jsonl-git-sync.mdx": __fd_glob_34, "prd/prd-010-contextual-learnings-system.mdx": __fd_glob_35, "prd/prd-010-dashboard-ux.mdx": __fd_glob_36, "prd/prd-011-claude-code-hooks.mdx": __fd_glob_37, "prd/prd-012-bun-single-binary.mdx": __fd_glob_38, "prd/prd-013-dashboard-ux.mdx": __fd_glob_39, "prd/prd-013-test-utilities.mdx": __fd_glob_40, "prd/prd-014-graph-schema-edges.mdx": __fd_glob_41, "prd/prd-015-jsonl-daemon-promotion.mdx": __fd_glob_42, "prd/prd-016-graph-expansion-retrieval.mdx": __fd_glob_43, "prd/prd-017-invalidation-maintenance.mdx": __fd_glob_44, "prd/prd-018-worker-orchestration.mdx": __fd_glob_45, "primitives/block.mdx": __fd_glob_46, "primitives/checkpoint.mdx": __fd_glob_47, "primitives/claim.mdx": __fd_glob_48, "primitives/context.mdx": __fd_glob_49, "primitives/docs.mdx": __fd_glob_50, "primitives/done.mdx": __fd_glob_51, "primitives/handoff.mdx": __fd_glob_52, "primitives/inbox.mdx": __fd_glob_53, "primitives/index.mdx": __fd_glob_54, "primitives/invariants.mdx": __fd_glob_55, "primitives/learning.mdx": __fd_glob_56, "primitives/ready.mdx": __fd_glob_57, "primitives/sync.mdx": __fd_glob_58, });