/**
 * Unit tests for formatTasksMarkdown in output.ts
 *
 * Tests the pure formatting function without DB access.
 * Uses in-memory TaskWithDeps objects to validate markdown output.
 */
import { describe, it, expect } from "vitest"
import { formatTasksMarkdown } from "../../apps/cli/src/output.js"
import type { ContextResult, LearningId, TaskId, TaskWithDeps } from "@jamesaphoenix/tx-types"

// Helper to create a minimal TaskWithDeps for testing
type TaskOverride =
  Omit<Partial<TaskWithDeps>, "id" | "description" | "blockedBy" | "blocks" | "children" | "effectiveGroupContextSourceTaskId"> & {
    id: string
    title: string
    description?: string | null
    blockedBy?: readonly string[]
    blocks?: readonly string[]
    children?: readonly string[]
    effectiveGroupContextSourceTaskId?: string | null
  }

const asTaskId = (value: string): TaskId => value as TaskId
const asLearningId = (value: number): LearningId => value as LearningId

function makeTask(overrides: TaskOverride): TaskWithDeps {
  const {
    id,
    title,
    description,
    blockedBy,
    blocks,
    children,
    effectiveGroupContextSourceTaskId,
    ...rest
  } = overrides

  return {
    id: asTaskId(id),
    title,
    status: "backlog",
    score: 500,
    description: description ?? "",
    parentId: null,
    assigneeType: null,
    assigneeId: null,
    assignedAt: null,
    assignedBy: null,
    metadata: {},
    createdAt: new Date("2026-02-28T10:00:00Z"),
    updatedAt: new Date("2026-02-28T10:00:00Z"),
    completedAt: null,
    blockedBy: (blockedBy ?? []).map(asTaskId),
    blocks: (blocks ?? []).map(asTaskId),
    children: (children ?? []).map(asTaskId),
    isReady: true,
    groupContext: null,
    effectiveGroupContext: null,
    effectiveGroupContextSourceTaskId: effectiveGroupContextSourceTaskId ? asTaskId(effectiveGroupContextSourceTaskId) : null,
    orchestrationStatus: null,
    claimedBy: null,
    claimExpiresAt: null,
    failedAttempts: 0,
    ...rest,
  }
}

describe("formatTasksMarkdown", () => {
  it("produces header with timestamp and instructions", () => {
    const md = formatTasksMarkdown([], [], { ready: 0, active: 0, blocked: 0, done: 0 })
    expect(md).toContain("# Task Queue")
    expect(md).toContain("Auto-generated by `tx md-export`")
    expect(md).toContain("Re-generate: `tx md-export`")
    expect(md).toContain("Complete a task: `tx done <id>`")
  })

  it("produces summary table with correct counts", () => {
    const md = formatTasksMarkdown([], [], { ready: 5, active: 2, blocked: 3, done: 10 })
    expect(md).toContain("| Ready  | 5 |")
    expect(md).toContain("| Active | 2 |")
    expect(md).toContain("| Blocked| 3 |")
    expect(md).toContain("| Done   | 10 |")
  })

  it("shows 'No ready tasks' when readyTasks is empty", () => {
    const md = formatTasksMarkdown([], [], { ready: 0, active: 0, blocked: 0, done: 0 })
    expect(md).toContain("_No ready tasks._")
    expect(md).not.toContain("by score, highest first")
  })

  it("renders ready tasks with numbered headings", () => {
    const tasks = [
      makeTask({ id: "tx-aaa111", title: "First Task", score: 900 }),
      makeTask({ id: "tx-bbb222", title: "Second Task", score: 700 }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 2, active: 0, blocked: 0, done: 0 })

    expect(md).toContain("### 1. tx-aaa111 — First Task")
    expect(md).toContain("### 2. tx-bbb222 — Second Task")
    expect(md).toContain("- **Score**: 900")
    expect(md).toContain("- **Score**: 700")
  })

  it("includes task description when present", () => {
    const tasks = [
      makeTask({ id: "tx-desc01", title: "Described Task", description: "Some important context" }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).toContain("- **Description**: Some important context")
  })

  it("omits description when empty", () => {
    const tasks = [
      makeTask({ id: "tx-nodesc", title: "No Description", description: "" }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).not.toContain("**Description**")
  })

  it("renders blockedBy and blocks info", () => {
    const tasks = [
      makeTask({
        id: "tx-dep001",
        title: "Task With Deps",
        blockedBy: ["tx-blocker1" as any],
        blocks: ["tx-downstream1" as any, "tx-downstream2" as any],
      }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).toContain("- **Blocked by**: tx-blocker1")
    expect(md).toContain("- **Blocks**: tx-downstream1, tx-downstream2")
  })

  it("shows '(none)' for empty blockedBy/blocks", () => {
    const tasks = [
      makeTask({ id: "tx-nodep", title: "Independent Task" }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).toContain("- **Blocked by**: (none)")
    expect(md).toContain("- **Blocks**: (none)")
  })

  it("includes children when present", () => {
    const tasks = [
      makeTask({
        id: "tx-parent",
        title: "Parent Task",
        children: ["tx-child1" as any, "tx-child2" as any],
      }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).toContain("- **Children**: tx-child1, tx-child2")
  })

  it("omits children line when empty", () => {
    const tasks = [makeTask({ id: "tx-nochild", title: "No Children" })]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).not.toContain("**Children**")
  })

  it("includes group context when present", () => {
    const tasks = [
      makeTask({
        id: "tx-ctx001",
        title: "Contextual Task",
        effectiveGroupContext: "auth-epic",
      }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).toContain("- **Group context**: auth-epic")
  })

  it("renders recently completed section", () => {
    const completed = [
      makeTask({
        id: "tx-done01",
        title: "Finished Task",
        status: "done",
        completedAt: new Date("2026-02-27T14:00:00Z"),
      }),
      makeTask({
        id: "tx-done02",
        title: "Another Done",
        status: "done",
        completedAt: new Date("2026-02-26T10:00:00Z"),
      }),
    ]
    const md = formatTasksMarkdown([], completed, { ready: 0, active: 0, blocked: 0, done: 2 })
    expect(md).toContain("## Recently Completed (last 2)")
    expect(md).toContain("- [x] tx-done01 — Finished Task (2026-02-27)")
    expect(md).toContain("- [x] tx-done02 — Another Done (2026-02-26)")
  })

  it("omits completed section when empty", () => {
    const tasks = [makeTask({ id: "tx-only", title: "Only Ready" })]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).not.toContain("## Recently Completed")
  })

  it("shows 'unknown' for completed tasks without completedAt", () => {
    const completed = [
      makeTask({ id: "tx-nodate", title: "No Date", status: "done", completedAt: null }),
    ]
    const md = formatTasksMarkdown([], completed, { ready: 0, active: 0, blocked: 0, done: 1 })
    expect(md).toContain("- [x] tx-nodate — No Date (unknown)")
  })

  it("includes learnings when includeContext is provided", () => {
    const tasks = [
      makeTask({ id: "tx-learn1", title: "Learned Task" }),
    ]
    const contextMap = new Map<string, ContextResult>()
    contextMap.set("tx-learn1", {
      taskId: "tx-learn1",
      taskTitle: "Learned Task",
      learnings: [
        {
          id: asLearningId(1),
          content: "Use JWT for auth",
          relevanceScore: 0.95,
          bm25Score: 0.95,
          vectorScore: 0,
          recencyScore: 0,
          rrfScore: 0.95,
          bm25Rank: 1,
          vectorRank: 0,
          category: "security",
          createdAt: new Date(),
          sourceType: "manual",
          sourceRef: null,
          keywords: [],
          usageCount: 0,
          lastUsedAt: null,
          outcomeScore: null,
          embedding: null,
        },
        {
          id: asLearningId(2),
          content: "Rotate refresh tokens",
          relevanceScore: 0.87,
          bm25Score: 0.87,
          vectorScore: 0,
          recencyScore: 0,
          rrfScore: 0.87,
          bm25Rank: 2,
          vectorRank: 0,
          category: null,
          createdAt: new Date(),
          sourceType: "manual",
          sourceRef: null,
          keywords: [],
          usageCount: 0,
          lastUsedAt: null,
          outcomeScore: null,
          embedding: null,
        },
      ],
      searchQuery: "learned task",
      searchDuration: 10,
    })

    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 }, {
      includeContext: contextMap,
    })

    expect(md).toContain("#### Learnings")
    expect(md).toContain("- [95%] Use JWT for auth")
    expect(md).toContain("- [87%] Rotate refresh tokens")
  })

  it("does not include learnings section when no learnings for a task", () => {
    const tasks = [
      makeTask({ id: "tx-nolearn", title: "No Learnings Task" }),
    ]
    const contextMap = new Map<string, ContextResult>()
    contextMap.set("tx-nolearn", {
      taskId: "tx-nolearn",
      taskTitle: "No Learnings Task",
      learnings: [],
      searchQuery: "no learnings task",
      searchDuration: 5,
    })

    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 }, {
      includeContext: contextMap,
    })
    expect(md).not.toContain("#### Learnings")
  })

  it("does not produce trailing separator when no completed tasks", () => {
    const tasks = [makeTask({ id: "tx-last", title: "Last Task" })]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    const trimmed = md.trimEnd()
    expect(trimmed).not.toMatch(/---$/)
  })

  it("produces separator between tasks when there are completed tasks", () => {
    const tasks = [
      makeTask({ id: "tx-a1", title: "Task A" }),
      makeTask({ id: "tx-b2", title: "Task B" }),
    ]
    const completed = [
      makeTask({ id: "tx-done1", title: "Done 1", status: "done", completedAt: new Date("2026-02-27") }),
    ]
    const md = formatTasksMarkdown(tasks, completed, { ready: 2, active: 0, blocked: 0, done: 1 })

    // Count standalone --- separator lines (not table separator rows like |--------|)
    const separatorLines = md.split("\n").filter(l => l.trim() === "---")
    // Should have: one after summary, one between task 1 and 2, one after task 2 before completed
    expect(separatorLines.length).toBe(3)
  })

  it("includes created date in YYYY-MM-DD format", () => {
    const tasks = [
      makeTask({ id: "tx-date01", title: "Dated Task", createdAt: new Date("2026-03-01T15:30:00Z") }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).toContain("- **Created**: 2026-03-01")
  })

  // --- Markdown escaping tests ---

  it("sanitizes task titles with backticks in headings", () => {
    const tasks = [
      makeTask({ id: "tx-esc001", title: "Fix `core` module" }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    // Backticks should be escaped in headings
    expect(md).toContain("### 1. tx-esc001 — Fix \\`core\\` module")
  })

  it("sanitizes task titles with brackets in headings", () => {
    const tasks = [
      makeTask({ id: "tx-esc002", title: "Task [alpha]" }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).toContain("\\[alpha\\]")
  })

  it("sanitizes task titles with angle brackets in headings", () => {
    const tasks = [
      makeTask({ id: "tx-esc006", title: "Fix <html> rendering" }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).toContain("\\<html\\>")
  })

  it("sanitizes group context with newlines", () => {
    const tasks = [
      makeTask({
        id: "tx-ctx002",
        title: "Context Task",
        effectiveGroupContext: "line1\nline2",
      }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).toContain("- **Group context**: line1 line2")
  })

  it("sanitizes learning content with newlines", () => {
    const tasks = [
      makeTask({ id: "tx-learn2", title: "Learn Task" }),
    ]
    const contextMap = new Map<string, ContextResult>()
    contextMap.set("tx-learn2", {
      taskId: "tx-learn2",
      taskTitle: "Learn Task",
      learnings: [
        {
          id: asLearningId(1),
          content: "First line\nSecond line",
          relevanceScore: 0.90,
          bm25Score: 0.9,
          vectorScore: 0,
          recencyScore: 0,
          rrfScore: 0.9,
          bm25Rank: 1,
          vectorRank: 0,
          category: null,
          createdAt: new Date(),
          sourceType: "manual",
          sourceRef: null,
          keywords: [],
          usageCount: 0,
          lastUsedAt: null,
          outcomeScore: null,
          embedding: null,
        },
      ],
      searchQuery: "learn task",
      searchDuration: 5,
    })

    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 }, {
      includeContext: contextMap,
    })
    expect(md).toContain("- [90%] First line Second line")
  })

  it("collapses newlines in titles to spaces", () => {
    const tasks = [
      makeTask({ id: "tx-esc003", title: "Line 1\nLine 2\rLine 3" }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    // Heading should be on a single line
    const headings = md.split("\n").filter(l => l.startsWith("### "))
    expect(headings.length).toBe(1)
    expect(headings[0]).toContain("Line 1 Line 2 Line 3")
  })

  it("collapses newlines in descriptions", () => {
    const tasks = [
      makeTask({ id: "tx-esc004", title: "Normal Title", description: "First line\nSecond line" }),
    ]
    const md = formatTasksMarkdown(tasks, [], { ready: 1, active: 0, blocked: 0, done: 0 })
    expect(md).toContain("**Description**: First line Second line")
  })

  it("sanitizes titles in recently completed section", () => {
    const completed = [
      makeTask({ id: "tx-esc005", title: "Fix [bug] in `core`", status: "done", completedAt: new Date("2026-02-27") }),
    ]
    const md = formatTasksMarkdown([], completed, { ready: 0, active: 0, blocked: 0, done: 1 })
    // Title in completed section should have newlines collapsed
    expect(md).toContain("tx-esc005")
    // Should not break the checkbox format
    expect(md).toMatch(/- \[x\] tx-esc005/)
  })
})
