/**
 * Output formatters for JSON/text CLI output
 */

import type { TaskWithDeps, TaskLinkedDocRef } from "@jamesaphoenix/tx/types"

// --- JSON serializer (handles Date objects) ---

function jsonReplacer(_key: string, value: unknown): unknown {
  if (value instanceof Date) return value.toISOString()
  return value
}

export function toJson(data: unknown): string {
  return JSON.stringify(data, jsonReplacer, 2)
}

// --- Task formatters ---

export function formatTaskWithDeps(t: TaskWithDeps): string {
  const lines = [
    `Task: ${t.id}`,
    `  Title: ${t.title}`,
    `  Status: ${t.status}`,
    `  Score: ${t.score}`,
    `  Ready: ${t.isReady ? "yes" : "no"}`,
  ]
  if (t.description) lines.push(`  Description: ${t.description}`)
  if (t.parentId) lines.push(`  Parent: ${t.parentId}`)
  lines.push(`  Blocked by: ${t.blockedBy.length > 0 ? t.blockedBy.join(", ") : "(none)"}`)
  lines.push(`  Blocks: ${t.blocks.length > 0 ? t.blocks.join(", ") : "(none)"}`)
  lines.push(`  Children: ${t.children.length > 0 ? t.children.join(", ") : "(none)"}`)
  if (t.linkedDocs.length > 0) {
    lines.push("  Linked docs:")
    for (const doc of t.linkedDocs) {
      lines.push(`    - ${formatLinkedDocText(doc)}`)
    }
  } else {
    lines.push("  Linked docs: (none)")
  }
  lines.push(`  Created: ${t.createdAt.toISOString()}`)
  lines.push(`  Updated: ${t.updatedAt.toISOString()}`)
  if (t.completedAt) lines.push(`  Completed: ${t.completedAt.toISOString()}`)
  return lines.join("\n")
}

export function formatTaskLine(t: TaskWithDeps): string {
  const readyMark = t.isReady ? "+" : " "
  return `  ${readyMark} ${t.id} [${t.status}] [${t.score}] ${t.title}`
}

export function formatReadyTaskLine(t: TaskWithDeps): string {
  const blocksInfo = t.blocks.length > 0 ? ` (unblocks ${t.blocks.length})` : ""
  return `  ${t.id} [${t.score}] ${t.title}${blocksInfo}`
}

// --- Markdown sanitization helpers ---

/** Sanitize text for use in markdown headings - collapse newlines and escape structural chars */
function sanitizeHeading(s: string): string {
  return s.replace(/[\r\n]+/g, " ").replace(/[`[\]<>]/g, "\\$&")
}

/** Sanitize text for use in markdown inline content - collapse newlines */
function sanitizeInline(s: string): string {
  return s.replace(/[\r\n]+/g, " ")
}

function formatLinkedDocText(doc: TaskLinkedDocRef): string {
  return `${doc.linkType}: ${doc.title} (${doc.kind}/${doc.name} v${doc.version})`
}

function formatLinkedDocMarkdown(doc: TaskLinkedDocRef): string {
  return `${sanitizeInline(doc.linkType)}: ${sanitizeInline(doc.title)} (${sanitizeInline(doc.kind)}/${sanitizeInline(doc.name)} v${doc.version})`
}

// --- Markdown export formatter ---

export interface TasksMarkdownOptions {
  /** Override the section title for the tasks list (default: "Ready Tasks") */
  sectionTitle?: string
  /** Override the empty state message for the tasks list. */
  emptyStateMessage?: string
}

export interface TasksMarkdownCounts {
  ready: number
  active: number
  blocked: number
  done: number
}

export function formatTasksMarkdown(
  readyTasks: readonly TaskWithDeps[],
  completedTasks: readonly TaskWithDeps[],
  allCounts: TasksMarkdownCounts,
  options: TasksMarkdownOptions = {}
): string {
  const now = new Date().toISOString()
  const lines: string[] = [
    `# Task Queue`,
    ``,
    `> Auto-generated by \`tx md-export\` at ${now}`,
    `> Re-generate: \`tx md-export\`  |  Complete a task: \`tx task done <id>\``,
    ``,
    `## Summary`,
    ``,
    `| Status | Count |`,
    `|--------|-------|`,
    `| Ready  | ${allCounts.ready} |`,
    `| Active | ${allCounts.active} |`,
    `| Blocked| ${allCounts.blocked} |`,
    `| Done   | ${allCounts.done} |`,
    ``,
    `---`,
    ``,
  ]

  const baseTitle = sanitizeHeading(options.sectionTitle ?? "Ready Tasks")
  const emptyStateMessage = options.emptyStateMessage ?? "_No ready tasks._"

  if (readyTasks.length === 0) {
    lines.push(`## ${baseTitle}`)
    lines.push(``)
    lines.push(emptyStateMessage)
    lines.push(``)
  } else {
    lines.push(`## ${baseTitle} (by score, highest first)`)
    lines.push(``)

    for (let i = 0; i < readyTasks.length; i++) {
      const t = readyTasks[i]
      lines.push(`### ${i + 1}. ${t.id} - ${sanitizeHeading(t.title)}`)
      lines.push(`- **Score**: ${t.score}`)
      lines.push(`- **Status**: ${t.status}`)
      if (t.description) lines.push(`- **Description**: ${sanitizeInline(t.description)}`)
      lines.push(`- **Blocked by**: ${t.blockedBy.length > 0 ? t.blockedBy.join(", ") : "(none)"}`)
      lines.push(`- **Blocks**: ${t.blocks.length > 0 ? t.blocks.join(", ") : "(none)"}`)
      if (t.children.length > 0) lines.push(`- **Children**: ${t.children.join(", ")}`)
      if (t.linkedDocs.length > 0) lines.push(`- **Linked docs**: ${t.linkedDocs.map(formatLinkedDocMarkdown).join("; ")}`)
      lines.push(`- **Created**: ${t.createdAt.toISOString().split("T")[0]}`)

      lines.push(``)
      // Add separator between tasks, and before completed section
      if (i < readyTasks.length - 1 || completedTasks.length > 0) {
        lines.push(`---`)
        lines.push(``)
      }
    }
  }

  if (completedTasks.length > 0) {
    lines.push(`## Recently Completed (last ${completedTasks.length})`)
    lines.push(``)
    for (const t of completedTasks) {
      const completedDate = t.completedAt ? t.completedAt.toISOString().split("T")[0] : "unknown"
      lines.push(`- [x] ${t.id} - ${sanitizeInline(t.title)} (${completedDate})`)
    }
    lines.push(``)
  }

  return lines.join("\n")
}

// --- Helpers ---

export function truncate(str: string, maxLen: number): string {
  return str.length > maxLen ? str.slice(0, maxLen) + "..." : str
}
