/**
 * CLI E2E Tests for tx md-export command
 *
 * Tests the following critical flows:
 * - One-shot export to markdown file
 * - Task ordering by score (highest first) — structural heading validation
 * - Summary table with correct counts
 * - Recently completed tasks section with correct dates
 * - Filter modes: ready, all, specific status names, invalid values
 * - Custom output path via --path
 * - JSON output via --json with schema validation
 * - Include completed tasks via --include-done (including edge cases: 0, negative)
 * - Empty database behavior
 * - Tasks with dependencies (blocked vs ready)
 * - Blocked tasks visible with --filter all
 * - Help text
 * - Markdown structural integrity (no trailing separators, well-formed headings)
 * - Interval validation
 *
 * Per DD-007: Uses real SQLite and deterministic test setup.
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest"
import { spawnSync } from "child_process"
import { mkdtempSync, rmSync, existsSync, readFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"

const CLI_SRC = resolve(__dirname, "../../apps/cli/src/cli.ts")
const CLI_TIMEOUT = Number(process.env.CLI_TEST_TIMEOUT ?? (process.env.CI ? 60000 : 30000))

/**
 * Force a WAL checkpoint on the database to ensure all writes from prior
 * subprocesses are visible to subsequent subprocess readers.
 */
function walCheckpoint(dbPath: string): void {
  const { Database } = require("bun:sqlite")
  const db = new Database(dbPath)
  db.exec("PRAGMA wal_checkpoint(TRUNCATE)")
  db.close()
}

interface ExecResult {
  stdout: string
  stderr: string
  status: number
}

function runTxArgs(args: string[], dbPath: string): ExecResult {
  try {
    const result = spawnSync("bun", [CLI_SRC, ...args, "--db", dbPath], {
      encoding: "utf-8",
      timeout: CLI_TIMEOUT,
      cwd: process.cwd()
    })
    return {
      stdout: result.stdout || "",
      stderr: result.stderr || "",
      status: result.status ?? 1
    }
  } catch (error: unknown) {
    const err = error as { stdout?: string; stderr?: string; status?: number }
    return {
      stdout: err.stdout || "",
      stderr: err.stderr || "",
      status: err.status ?? 1
    }
  }
}

function runTx(args: string, dbPath: string): ExecResult {
  return runTxArgs(args.split(" "), dbPath)
}

// =============================================================================
// tx md-export Command Tests
// =============================================================================

describe("CLI md-export command", () => {
  let tmpDir: string
  let dbPath: string

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "tx-test-md-export-"))
    dbPath = join(tmpDir, "test.db")
    // Initialize database
    runTx("init", dbPath)
  })

  afterEach(() => {
    if (existsSync(tmpDir)) {
      rmSync(tmpDir, { recursive: true, force: true })
    }
  })

  // ---------------------------------------------------------------------------
  // 1. Basic one-shot export
  // ---------------------------------------------------------------------------

  describe("basic export", () => {
    it("exports ready tasks to markdown file", () => {
      runTxArgs(["add", "Task Alpha", "--score", "800", "--json"], dbPath)
      walCheckpoint(dbPath)
      runTxArgs(["add", "Task Beta", "--score", "600", "--json"], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath], dbPath)

      expect(result.status).toBe(0)
      expect(result.stdout).toContain("Exported")
      expect(result.stdout).toContain("ready tasks")

      expect(existsSync(mdPath)).toBe(true)
      const content = readFileSync(mdPath, "utf-8")

      expect(content).toContain("# Task Queue")
      expect(content).toContain("Auto-generated by `tx md-export`")
      expect(content).toContain("## Summary")
      expect(content).toContain("| Status | Count |")
      expect(content).toContain("Task Alpha")
      expect(content).toContain("Task Beta")
    })

    it("sorts ready tasks by score highest first — verified via heading structure", () => {
      runTxArgs(["add", "Low Priority", "--score", "100", "--json"], dbPath)
      walCheckpoint(dbPath)
      runTxArgs(["add", "High Priority", "--score", "900", "--json"], dbPath)
      walCheckpoint(dbPath)
      runTxArgs(["add", "Medium Priority", "--score", "500", "--json"], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")

      // Verify ordering via heading lines — most reliable structural check
      const headings = content.split("\n").filter(l => l.startsWith("### "))
      expect(headings.length).toBe(3)
      expect(headings[0]).toContain("High Priority")
      expect(headings[1]).toContain("Medium Priority")
      expect(headings[2]).toContain("Low Priority")

      // Verify numbering
      expect(headings[0]).toMatch(/^### 1\./)
      expect(headings[1]).toMatch(/^### 2\./)
      expect(headings[2]).toMatch(/^### 3\./)
    })

    it("shows correct summary counts", () => {
      const t1 = runTxArgs(["add", "Ready Task", "--json"], dbPath)
      walCheckpoint(dbPath)
      const t1Id = JSON.parse(t1.stdout).id

      runTxArgs(["add", "Another Ready Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      runTxArgs(["done", t1Id], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      expect(content).toMatch(/\| Done\s+\|\s*[1-9]/)
      // Ready count should be >= 1 (the remaining ready task)
      expect(content).toMatch(/\| Ready\s+\|\s*[1-9]/)
    })
  })

  // ---------------------------------------------------------------------------
  // 2. Empty database
  // ---------------------------------------------------------------------------

  describe("empty database", () => {
    it("handles empty database gracefully", () => {
      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath], dbPath)

      expect(result.status).toBe(0)
      expect(result.stdout).toContain("Exported 0 ready tasks")

      const content = readFileSync(mdPath, "utf-8")
      expect(content).toContain("# Task Queue")
      expect(content).toContain("_No ready tasks._")
      // All counts should be 0
      expect(content).toContain("| Ready  | 0 |")
      expect(content).toContain("| Done   | 0 |")
    })
  })

  // ---------------------------------------------------------------------------
  // 3. Dependencies: blocked tasks should NOT appear in ready export
  // ---------------------------------------------------------------------------

  describe("dependency handling", () => {
    it("only exports ready (unblocked) tasks when using default filter", () => {
      const blocker = runTxArgs(["add", "Blocker Task", "--score", "800", "--json"], dbPath)
      walCheckpoint(dbPath)
      const blockerId = JSON.parse(blocker.stdout).id

      const blocked = runTxArgs(["add", "Blocked Task", "--score", "900", "--json"], dbPath)
      walCheckpoint(dbPath)
      const blockedId = JSON.parse(blocked.stdout).id

      runTxArgs(["block", blockedId, blockerId], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      const readySection = content.split("## Ready Tasks")[1] || ""
      expect(readySection).toContain("Blocker Task")
      expect(readySection).not.toContain("Blocked Task")
    })

    it("shows blocked tasks with --filter all including blockedBy info", () => {
      const blocker = runTxArgs(["add", "Auth Blocker", "--score", "800", "--json"], dbPath)
      walCheckpoint(dbPath)
      const blockerId = JSON.parse(blocker.stdout).id

      const blocked = runTxArgs(["add", "Blocked Auth", "--score", "900", "--json"], dbPath)
      walCheckpoint(dbPath)
      const blockedId = JSON.parse(blocked.stdout).id

      runTxArgs(["block", blockedId, blockerId], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--filter", "all"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      // Both tasks should appear in --filter all
      expect(content).toContain("Auth Blocker")
      expect(content).toContain("Blocked Auth")
      // The blocked task should show its blocker ID
      expect(content).toContain(blockerId)
    })
  })

  // ---------------------------------------------------------------------------
  // 4. Include completed tasks (--include-done)
  // ---------------------------------------------------------------------------

  describe("--include-done", () => {
    it("includes recently completed tasks with correct checkbox format and date", () => {
      const t1 = runTxArgs(["add", "Done Task One", "--json"], dbPath)
      walCheckpoint(dbPath)
      const t1Id = JSON.parse(t1.stdout).id

      const t2 = runTxArgs(["add", "Done Task Two", "--json"], dbPath)
      walCheckpoint(dbPath)
      const t2Id = JSON.parse(t2.stdout).id

      runTxArgs(["add", "Still Ready Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      runTxArgs(["done", t1Id], dbPath)
      walCheckpoint(dbPath)
      runTxArgs(["done", t2Id], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--include-done", "10"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      expect(content).toContain("## Recently Completed")
      expect(content).toContain("Done Task One")
      expect(content).toContain("Done Task Two")

      // Verify checkbox format: - [x] <id> — <title> (<date>)
      const today = new Date().toISOString().split("T")[0]
      expect(content).toMatch(new RegExp(`- \\[x\\] ${t1Id} — Done Task One \\(${today}\\)`))
      expect(content).toMatch(new RegExp(`- \\[x\\] ${t2Id} — Done Task Two \\(${today}\\)`))
    })

    it("limits completed tasks to specified count", { timeout: CLI_TIMEOUT }, () => {
      for (let i = 1; i <= 3; i++) {
        const t = runTxArgs(["add", `Completed ${i}`, "--json"], dbPath)
        walCheckpoint(dbPath)
        const id = JSON.parse(t.stdout).id
        runTxArgs(["done", id], dbPath)
        walCheckpoint(dbPath)
      }

      runTxArgs(["add", "Ready Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--include-done", "1"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      expect(content).toContain("Recently Completed (last 1)")
      // Verify exactly 1 completed task entry is rendered
      const completedLines = content.split("\n").filter(l => /^- \[x\]/.test(l))
      expect(completedLines.length).toBe(1)
    })

    it("excludes completed section when --include-done 0", () => {
      const t = runTxArgs(["add", "Done Task", "--json"], dbPath)
      walCheckpoint(dbPath)
      const tId = JSON.parse(t.stdout).id
      runTxArgs(["done", tId], dbPath)
      walCheckpoint(dbPath)

      runTxArgs(["add", "Ready Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--include-done", "0"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      expect(content).not.toContain("## Recently Completed")
    })

    it("treats negative --include-done the same as 0 (no completed section)", () => {
      const t = runTxArgs(["add", "Done Task", "--json"], dbPath)
      walCheckpoint(dbPath)
      const tId = JSON.parse(t.stdout).id
      runTxArgs(["done", tId], dbPath)
      walCheckpoint(dbPath)

      runTxArgs(["add", "Ready Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--include-done", "-1"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      expect(content).not.toContain("## Recently Completed")
    })
  })

  // ---------------------------------------------------------------------------
  // 5. Custom output path (--path)
  // ---------------------------------------------------------------------------

  describe("--path", () => {
    it("writes to custom path", () => {
      runTxArgs(["add", "Test Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      const customPath = join(tmpDir, "custom", "output.md")
      const result = runTxArgs(["md-export", "--path", customPath], dbPath)

      expect(result.status).toBe(0)
      expect(existsSync(customPath)).toBe(true)

      const content = readFileSync(customPath, "utf-8")
      expect(content).toContain("Test Task")
    })

    it("creates parent directories if they do not exist", () => {
      runTxArgs(["add", "Test Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      const deepPath = join(tmpDir, "deep", "nested", "dir", "tasks.md")
      const result = runTxArgs(["md-export", "--path", deepPath], dbPath)

      expect(result.status).toBe(0)
      expect(existsSync(deepPath)).toBe(true)
    })
  })

  // ---------------------------------------------------------------------------
  // 6. JSON output (--json) — validated schema
  // ---------------------------------------------------------------------------

  describe("--json output", () => {
    it("outputs valid JSON with correct metadata", () => {
      runTxArgs(["add", "JSON Test Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--json"], dbPath)

      expect(result.status).toBe(0)

      const json = JSON.parse(result.stdout)
      expect(json).toHaveProperty("path")
      expect(json).toHaveProperty("readyCount")
      expect(json).toHaveProperty("completedCount")
      expect(json).toHaveProperty("counts")
      expect(json.counts).toHaveProperty("ready")
      expect(json.counts).toHaveProperty("active")
      expect(json.counts).toHaveProperty("blocked")
      expect(json.counts).toHaveProperty("done")

      // Validate actual values
      expect(json.readyCount).toBeGreaterThanOrEqual(1)
      expect(json.completedCount).toBe(0)
      expect(json.path).toBe(mdPath)
      expect(typeof json.counts.ready).toBe("number")
      expect(typeof json.counts.done).toBe("number")
    })
  })

  // ---------------------------------------------------------------------------
  // 7. Filter modes — comprehensive
  // ---------------------------------------------------------------------------

  describe("--filter", () => {
    it("filters by all shows every task regardless of status", () => {
      const t1 = runTxArgs(["add", "Task One", "--json"], dbPath)
      walCheckpoint(dbPath)
      const t1Id = JSON.parse(t1.stdout).id

      runTxArgs(["add", "Task Two", "--json"], dbPath)
      walCheckpoint(dbPath)

      runTxArgs(["done", t1Id], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--filter", "all"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      expect(content).toContain("Task One")
      expect(content).toContain("Task Two")
      // Both tasks should appear in the main section headings (not just in completed section)
      const headings = content.split("\n").filter(l => l.startsWith("### "))
      const hasTaskOne = headings.some(h => h.includes("Task One"))
      const hasTaskTwo = headings.some(h => h.includes("Task Two"))
      expect(hasTaskOne).toBe(true)
      expect(hasTaskTwo).toBe(true)
    })

    it("filters by specific status name (backlog)", () => {
      runTxArgs(["add", "Backlog Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--filter", "backlog"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      expect(content).toContain("Backlog Task")
    })

    it("filters by done status shows only done tasks in main section", () => {
      const t1 = runTxArgs(["add", "Will Be Done", "--json"], dbPath)
      walCheckpoint(dbPath)
      const t1Id = JSON.parse(t1.stdout).id

      runTxArgs(["add", "Still Ready", "--json"], dbPath)
      walCheckpoint(dbPath)

      runTxArgs(["done", t1Id], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--filter", "done"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      // Main section should have the done task
      expect(content).toContain("Will Be Done")
      // Ready task should NOT be in the main task section (headed by ###)
      const headings = content.split("\n").filter(l => l.startsWith("### "))
      const hasStillReady = headings.some(h => h.includes("Still Ready"))
      expect(hasStillReady).toBe(false)
    })

    it("rejects invalid filter values", () => {
      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--filter", "bogus"], dbPath)

      expect(result.status).not.toBe(0)
      expect(result.stderr).toContain("Invalid --filter")
    })

    it("--filter with --include-done are independent", () => {
      const t1 = runTxArgs(["add", "Done Task", "--json"], dbPath)
      walCheckpoint(dbPath)
      const t1Id = JSON.parse(t1.stdout).id

      runTxArgs(["add", "Ready Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      runTxArgs(["done", t1Id], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      // --filter ready only shows ready in main section, but --include-done still shows completed
      const result = runTxArgs(["md-export", "--path", mdPath, "--filter", "ready", "--include-done", "10"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      // Main section should only have the ready task
      const headings = content.split("\n").filter(l => l.startsWith("### "))
      expect(headings.length).toBe(1)
      expect(headings[0]).toContain("Ready Task")
      // But completed section should still exist
      expect(content).toContain("## Recently Completed")
      expect(content).toContain("Done Task")
    })
  })

  // ---------------------------------------------------------------------------
  // 8. Task details in markdown
  // ---------------------------------------------------------------------------

  describe("task details", () => {
    it("includes score, status, and description in markdown", () => {
      runTxArgs(["add", "Detailed Task", "--score", "750", "--description", "A task with a description", "--json"], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      expect(content).toContain("**Score**: 750")
      expect(content).toContain("**Description**: A task with a description")
    })

    it("includes blocking relationship with actual task IDs", () => {
      const t1 = runTxArgs(["add", "Blocker Task", "--json"], dbPath)
      walCheckpoint(dbPath)
      const blockerId = JSON.parse(t1.stdout).id

      const t2 = runTxArgs(["add", "Other Task", "--json"], dbPath)
      walCheckpoint(dbPath)
      const otherId = JSON.parse(t2.stdout).id

      runTxArgs(["block", otherId, blockerId], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      // Blocker task should show it blocks the other task
      expect(content).toContain(`**Blocks**: ${otherId}`)
    })
  })

  // ---------------------------------------------------------------------------
  // 9. Help text
  // ---------------------------------------------------------------------------

  describe("help", () => {
    it("shows help with --help flag", () => {
      const result = runTxArgs(["md-export", "--help"], dbPath)
      expect(result.status).toBe(0)
      expect(result.stdout).toContain("tx md-export")
      expect(result.stdout).toContain("--path")
      expect(result.stdout).toContain("--filter")
      expect(result.stdout).toContain("--watch")
      expect(result.stdout).toContain("--include-context")
      expect(result.stdout).toContain("--include-done")
      expect(result.stdout).toContain("--interval")
    })

    it("shows help via tx help md-export", () => {
      const result = runTxArgs(["help", "md-export"], dbPath)
      expect(result.status).toBe(0)
      expect(result.stdout).toContain("tx md-export")
    })
  })

  // ---------------------------------------------------------------------------
  // 10. Markdown format structure validation
  // ---------------------------------------------------------------------------

  describe("markdown structure", () => {
    it("produces well-formed markdown with all sections", () => {
      const t1 = runTxArgs(["add", "Completed Task", "--score", "500", "--json"], dbPath)
      walCheckpoint(dbPath)
      const t1Id = JSON.parse(t1.stdout).id

      runTxArgs(["add", "Ready Task A", "--score", "800", "--json"], dbPath)
      walCheckpoint(dbPath)
      runTxArgs(["add", "Ready Task B", "--score", "600", "--json"], dbPath)
      walCheckpoint(dbPath)

      runTxArgs(["done", t1Id], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--include-done", "5"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")

      // Validate full markdown structure
      expect(content).toContain("# Task Queue")
      expect(content).toContain("> Auto-generated by `tx md-export`")
      expect(content).toContain("> Re-generate: `tx md-export`")
      expect(content).toContain("## Summary")
      expect(content).toContain("| Status | Count |")
      expect(content).toContain("## Ready Tasks (by score, highest first)")
      expect(content).toContain("## Recently Completed")

      // Validate task entries have required fields
      expect(content).toContain("**Score**:")
      expect(content).toContain("**Status**:")
      expect(content).toContain("**Blocked by**:")
      expect(content).toContain("**Blocks**:")
      expect(content).toContain("**Created**:")
    })

    it("does not produce trailing separator when no completed tasks", () => {
      runTxArgs(["add", "Only Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--include-done", "0"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      const trimmed = content.trimEnd()
      expect(trimmed).not.toMatch(/---$/)
    })
  })

  // ---------------------------------------------------------------------------
  // 11. Edge case: interval validation
  // ---------------------------------------------------------------------------

  describe("interval validation", () => {
    it("rejects --interval 0 in watch mode", () => {
      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--watch", "--interval", "0"], dbPath)

      expect(result.status).not.toBe(0)
      expect(result.stderr).toContain("Invalid --interval")
    })
  })

  // ---------------------------------------------------------------------------
  // 12. Children in task output
  // ---------------------------------------------------------------------------

  describe("children", () => {
    it("includes children in task detail when children exist", () => {
      const parent = runTxArgs(["add", "Parent Task", "--json"], dbPath)
      walCheckpoint(dbPath)
      const parentId = JSON.parse(parent.stdout).id

      runTxArgs(["add", "Child Task", "--parent", parentId, "--json"], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      expect(content).toContain("**Children**:")
    })
  })

  // ---------------------------------------------------------------------------
  // 13. Special characters in task titles (escaping)
  // ---------------------------------------------------------------------------

  describe("special character escaping", () => {
    it("escapes special markdown characters in task titles", () => {
      runTxArgs(["add", "Fix `core` [alpha] module", "--json"], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      const headings = content.split("\n").filter(l => l.startsWith("### "))
      expect(headings.length).toBeGreaterThanOrEqual(1)
      expect(headings[0]).toContain("\\`core\\`")
      expect(headings[0]).toContain("\\[alpha\\]")
    })
  })

  // ---------------------------------------------------------------------------
  // 14. Filter section title
  // ---------------------------------------------------------------------------

  describe("filter section title", () => {
    it("shows 'All Tasks' heading when --filter all", () => {
      runTxArgs(["add", "Some Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--filter", "all"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      expect(content).toContain("## All Tasks (by score, highest first)")
    })

    it("shows correct ready count in summary when --filter all", () => {
      // Create one ready task and one done task
      runTxArgs(["add", "Ready Task", "--json"], dbPath)
      walCheckpoint(dbPath)

      const t2 = runTxArgs(["add", "Done Task", "--json"], dbPath)
      walCheckpoint(dbPath)
      const t2Id = JSON.parse(t2.stdout).id
      runTxArgs(["done", t2Id], dbPath)
      walCheckpoint(dbPath)

      const mdPath = join(tmpDir, "tasks.md")
      const result = runTxArgs(["md-export", "--path", mdPath, "--filter", "all"], dbPath)
      expect(result.status).toBe(0)

      const content = readFileSync(mdPath, "utf-8")
      // Summary table should show real ready count (1), not total filtered count (2)
      expect(content).toContain("| Ready  | 1 |")
    })
  })
})
